version: "3"

environment:
  - RACK_ENV=development
  - SHOW=true
  - SESSION_SECRET
services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./:/usr/share/nginx/html
